services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_blog_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:15
    container_name: mini_blog_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  mongodb:
    image: mongo:8
    container_name: mini_blog_mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db    

  redis:
    image: redis:8
    container_name: mini_blog_redis
    ports:
      - "6379:6379"    

volumes:
  postgres_data:
  mongodb_data:    